### ISSUE TITLE
Broken for certain sites

### ISSUE THREAD

**Issue by DamonFriedberg** [tjg1/nori#101]
On rule34.xxx - thumbnails load, full images don't.
On gelbooru.com - neither thumbnail nor full images load, tags and everything show up though.

**Comment by tjg1** [comment]
Thanks for the report. Can you try the latest build from develop?

[app-fdroid-release.apk.zip](https://github.com/tjg1/nori/files/853129/app-fdroid-release.apk.zip)

**Comment by tjg1** [comment]
Confirmed working in latest `develop`.

**Comment by DamonFriedberg** [comment]
Thanks. Guess I just needed a fresh install.

**Comment by tjg1** [comment]
That means the problem should be fixed in the next release. (start of next month)
