### ISSUE TITLE
Trying to view images on Danbooru  not working

### ISSUE THREAD

**Issue by Luxray5474** [tjg1/nori#122]
It spits out this

"Unable to resolve host "danbooru.donmai.ushttps": no address associated with hostname"

In settings, I set the name of the service to 'danbooru' and the URL to 'https://danbooru.donmai.us', and with no Username or Password/APIkey.

**Comment by shisawatari** [comment]
I second this. I have the same problem. Here you have some screenshots:
![screenshot_20180617-143131](https://user-images.githubusercontent.com/40336126/41507884-d187c3aa-723b-11e8-8585-924c93d275d9.png)
![screenshot_20180617-143204](https://user-images.githubusercontent.com/40336126/41507885-d63efb98-723b-11e8-9f7b-ab8b8977fdcd.png)

**Comment by nyk-jpg** [comment]
I am having this issue as well. Danbooru is pretty much the only reason I download Nori, too.. Would be nice to see some kind of response to this issue.

**Comment by Luxray5474** [comment]
For the meantime I've switched to Anime Boxes. It's pretty solid but lacks some features Nori has.

On Sep 3, 2018 09:05, nyk-jpg <notifications@github.com> wrote:

I am having this issue as well. Danbooru is pretty much the only reason I download Nori, too.. Would be nice to see some kind of response to this issue.

**Comment by tjg1** [comment]
I believe this was fixed in a3368960399589388c0f6c021cb847d253078a16 and remains broken in the F-Droid build because of #124 .
