### ISSUE TITLE
Activity refactor

### ISSUE THREAD

**Issue by tjg1** [tjg1/nori#48]
The code of some Activities is getting really messy and it would be nice to split out some subclasses (especially adapters) into their own files.

**Comment by myozka** [comment]
I think there are two ways to go with this.
1. One is to create another package for adapters -> `io.github.tjg1.nori.adapter`. That requires some class variables and methods to be made **_public_** (which are **_private_** at the moment).
2. The other one is to keep them in the same package `io.github.tjg1.nori`. That requires some class variables and methods to be made **_no-modifier_**, or **_protected_**.
