### ISSUE TITLE
Danbooru Account Login

### ISSUE THREAD

**Issue by kurohai** [tjg1/nori#52]
After entering my account info while setting up Danbooru, I am unable to search for more than two tags. The two tag search limit applies to anon and free accounts only. I have a Platinum account which allows six tags.

I haven't tried to log in with an account with any other site. Danbooru is the only site I have an account for.

**Comment by tjg1** [comment]
I've emailed Danbooru to see if they can provide me with a free account upgrade to test this with.

**Comment by tjg1** [comment]
@reiyasona This has already been fixed. Download v2.3.0 from Github or F-Droid.
