### ISSUE TITLE
Submodule initialization problems after a fresh repo cloning

### ISSUE THREAD

**Issue by ladSuematsu** [tjg1/nori#64]
I would like to warn I found some problems after cloning your repo. I couldn't initialize the git submodules used by the project. I suggest a review and cleaning of the repo's submodule configurations.

**Submodule norilib**
The submodule is pointing to a invalid commit. Maybe the submodule repo code was changed and the last submodule reference update in the main repo was not commited/pushed?

```
$ git submodule init
Submodule 'norilib' (https://github.com/tjg1/norilib.git) registered for path 'norilib'

$ git submodule update
Cloning into 'norilib'...
remote: Counting objects: 1452, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1452 (delta 0), reused 0 (delta 0), pack-reused 1440
Receiving objects: 100% (1452/1452), 447.19 KiB | 370.00 KiB/s, done.
Resolving deltas: 100% (479/479), done.
Checking connectivity... done.
fatal: reference is not a tree: 99d0688301e1593d9e255f6b27065167444b7cb0
Unable to checkout '99d0688301e1593d9e255f6b27065167444b7cb0' in submodule path 'norilib'
```

**Submodule SearchViewAllowEmpty**
Though it is listed in the .gitmodules file, It does not exist anymore in your repo list, nor it is configured in the project's settings.gradle .

```
$ git submodule init SearchViewAllowEmpty
error: pathspec 'SearchViewAllowEmpty' did not match any file(s) known to git.
```

**Comment by myozka** [comment]
I've faced the same problem, too. There is a problem with the mentioned commit id from norilib. I've re-initialized the submodule after cloning. And, the pull request I've sent updates the module files to resolve this issue.

**Comment by tjg1** [comment]
Sorry, guys. I've simply forgotten to push the latest commit to GitHub. It should work now.
