### ISSUE TITLE
Flickr as default service

### ISSUE THREAD

**Issue by bigretromike** [tjg1/nori#79]
Is there any guide how to obtain api url for other things.
Also if safebooru aint default please update descriptions as f-droid version is missing it (booru)

**Comment by tjg1** [comment]
Just use the root URL (i.e. http://safebooru.org/), Nori will detect API endpoints automatically. The F-Droid version should autocomplete names of supported services and fill in the URL for you.

App developers don't have direct control over F-Droid builds/listings. I will open a pull request to update the description and make sure they're using the correct product flavour.

**Comment by tjg1** [comment]
Adding services will be made easier in the future. Sorry if you found it confusing.

**Comment by bigretromike** [comment]
You are right :-)
Thank you for adding this kind of feature, its useful
