### ISSUE TITLE
Public list of services

### ISSUE THREAD

**Issue by flasheater** [tjg1/nori#84]
I am curious what services other people have plugged in. 

Why does nori come with only one shipped ?

**Comment by tjg1** [comment]
The FOSS (F-Droid) build ships with Safebooru as the default service and supports URL auto-completion for other popular supported services: take a look here: [arrays.xml#L46](https://github.com/tjg1/nori/blob/ea3cb6cd70bfef42a1667d6fccd4c49aea4a4078/app/src/main/res/values/arrays.xml#L46)

The Google Play build ships with Flickr as the default service and has no URL auto-completion - it still supports the same services, you just have to configure them manually. 

The reason that some features are missing in the Play Store version of the app is that Play Store's anti-malware 'Gatekeeper' scans submitted apps for NSFW URLs and strings - you can read more about how that affected Nori's development on my blog: https://tjg1.github.io/post/nori-removed-from-the-play-store

I'm currently working to add support for more services to Nori - making it more of a general purpose image gallery app: https://tjg1.github.io/post/future-of-nori-and-norilib

I hope this answers your question.

**Comment by flasheater** [comment]
Nice, that explains it then. Is the auto-completion feature docuemted and I simply overlooked it?
Btw, the current F-Droid version 3.1.0 of nori shipped with Flickr as defaut. The Auto-completion is enabled.

**Comment by tjg1** [comment]
It seems I've set it to Flickr in both builds. I think the issue with Safebooru was that Nori was showing the most recently uploaded images by default, and sometimes porn that was incorrectly marked "safe" would pop up. https://github.com/tjg1/nori/commit/593343c4805bc6a23c565cfdaee84c0c07bd4380
