### ISSUE TITLE
Can't work for konachan

### ISSUE THREAD

**Issue by LoIIipop** [tjg1/nori#86]
Can't display image

**Comment by XyLoNaMiyX** [comment]
It seems like the image is downloaded (because it's not "instant"), but the shown image is white:

<img height="420px" alt="Bug" src="https://cloud.githubusercontent.com/assets/6297805/22335815/648a53ca-e3e0-11e6-8cf5-6ddc2cf6e1f8.png" />

_Gray = Not loaded; White = Loaded_.

**Comment by LoIIipop** [comment]
But in fact these pictures are not white.

**Comment by XyLoNaMiyX** [comment]
I found that the images url's is something like:
`https://konachan.com//konachan.com/data/preview/b4/17/b417af744b94cb27d2be269a1eb833a8.jpg`

The mistake is obvious. It should rather be:
`https://konachan.com/data/preview/b4/17/b417af744b94cb27d2be269a1eb833a8.jpg`

For Flickr (for instance) however, it works just fine:
`https://farm1.staticflickr.com/325/31703099373_49e9a22c56_q.jpg`

**Comment by XyLoNaMiyX** [comment]
I've fixed it on [this](https://github.com/tjg1/norilib/pull/16) pull request for [`norilib`](https://github.com/tjg1/norilib).

If you _really_ need this fix right away @LoIIipop, you can use [my fork](https://github.com/LonamiWebs/norilib) instead and compile the application yourself 😋 I'll be using a custom build meanwhile.

**Comment by tjg1** [comment]
Thanks for the pull request. I'll try to get it reviewed and merged later today On 26 Jan 2017 16:10, Lonami <notifications@github.com> wrote:I've fixed it on this pull request for norilib.
If you really need this fix right away @LoIIipop, you can use my fork instead and compile the application yourself 😋 I'll be using a custom build meanwhile.
